modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"
issueTrackerURL="https://github.com/Tak-min/orpheusInMineCraft/issues"

[[mods]]
    modId="orpheus"
    version="2.0.1"
    displayName="orpheus_in_minecraft"
    displayURL="NONE"
    logoFile="orpheus.png"
    authors="Takmin"
    description="We just need a orpheus to be happy"

[[dependencies.orpheus]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.orpheus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.orpheus]]
    modId="curios"
    mandatory=true
    versionRange="[5.14.1+1.20.1,)"
    ordering="NONE"
    side="BOTH"