# This is the mod's metadata file. It contains properties specific to the mod.
modLoader="javafml" # Forge is a extension of the FML framework
loaderVersion="[54,)" # Forge 1.21.4 uses loader version 54 and up
license="All Rights Reserved" # Your mod license

[[mods]]
modId="justkiddinghostiles"
version="1.0.0"
displayName="Just Kidding Hostiles"
description='''
"Ever wish those monsters were a bit more... friendly?"

If so, this is the mod for you!
This mod adds "Just Kidding Hostiles" to your world!

They may look just like the fearsome monsters you know, but their nature is completely different.
They might approach you when they see you, but not to attack—they're just curious!

Our first addition is the "Mini Zombie."
It's a tiny, harmless zombie that will toddle along behind you.

We plan to add many more "just kidding" friends in future updates!
Please enjoy a Minecraft world that's a little less scary and a lot more cute.
'''

# Dependencies for your mod
[[dependencies.justkiddinghostiles]]
modId="forge"
mandatory=true
versionRange="[54,)"
ordering="NONE"
side="BOTH"

[[dependencies.justkiddinghostiles]]
modId="minecraft"
mandatory=true
versionRange="[1.21.4,)"
ordering="NONE"
side="BOTH"